name: Deploy Gift of Hope Website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Get project files
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Prepare website
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy website
        uses: actions/deploy-pages@v4
